import type { Project, Investment, Transaction, Portfolio } from '@/types';

type ProjectStatus = 'privatesale' | 'PRESALE' | 'WHITELISTING' | 'ANNOUNCEMENT' | 'PRESALEANNOUNCEMENT' | 'PUBLIC' | 'FINISHED';

interface ExtendedProject extends Omit<Project, 'status'> {
  status: ProjectStatus;
  announcement_date?: string;
  presale_start_date?: string;
  is_whitelisted?: boolean;
}

export const mockProjects: ExtendedProject[] = [
  {
    id: '1',
    title: 'Wohnungsanlage Baden bei Wien',
    description: '24 moderne Wohnungen in historischer Kurstadt mit stabiler Mietrendite und Wertsteigerungspotential.',
    location: 'Baden bei Wien, AT',
    target_amount: 14000000,
    raised_amount: 4900000,
    minimum_investment: 1000,
    expected_return: 4.0,
    duration_months: 36,
    image_url: 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=800',
    status: 'PUBLIC',
    created_at: '2024-01-15',
    tenant_id: 'default',
  },
  {
    id: '2',
    title: 'Manhattan Luxury Condos',
    description: 'Premium residential development in prime Manhattan location with luxury amenities.',
    location: 'New York, NY',
    target_amount: 5000000,
    raised_amount: 0,
    minimum_investment: 2500,
    expected_return: 18.5,
    duration_months: 48,
    image_url: 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg?auto=compress&cs=tinysrgb&w=800',
    status: 'privatesale',
    created_at: '2024-01-10',
    tenant_id: 'default',
    is_whitelisted: true,
  },
  {
    id: '3',
    title: 'Austin Tech Campus',
    description: 'Modern office complex designed for tech companies with flexible workspaces.',
    location: 'Austin, TX',
    target_amount: 3500000,
    raised_amount: 0,
    minimum_investment: 500,
    expected_return: 16.0,
    duration_months: 24,
    image_url: 'https://images.pexels.com/photos/380769/pexels-photo-380769.jpeg?auto=compress&cs=tinysrgb&w=800',
    status: 'PRESALE',
    created_at: '2024-01-05',
    tenant_id: 'default',
  },
  {
    id: '4',
    title: 'Denver Mountain Lodge',
    description: 'Boutique mountain lodge with ski-in/ski-out access and luxury accommodations.',
    location: 'Denver, CO',
    target_amount: 2500000,
    raised_amount: 0,
    minimum_investment: 750,
    expected_return: 20.5,
    duration_months: 30,
    image_url: 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=800',
    status: 'WHITELISTING',
    created_at: '2024-01-20',
    tenant_id: 'default',
  },
  {
    id: '5',
    title: 'Miami Beach Resort',
    description: 'Beachfront resort and spa development with ocean views and world-class amenities.',
    location: 'Miami Beach, FL',
    target_amount: 8000000,
    raised_amount: 0,
    minimum_investment: 2000,
    expected_return: 22.0,
    duration_months: 48,
    image_url: 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg?auto=compress&cs=tinysrgb&w=800',
    status: 'ANNOUNCEMENT',
    announcement_date: '2024-03-15',
    created_at: '2024-01-25',
    tenant_id: 'default',
  },
  {
    id: '6',
    title: 'Berlin Office Complex',
    description: 'Modern office building in Berlin\'s financial district with premium tenants.',
    location: 'Berlin, DE',
    target_amount: 6000000,
    raised_amount: 0,
    minimum_investment: 1500,
    expected_return: 14.5,
    duration_months: 36,
    image_url: 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=800',
    status: 'PRESALEANNOUNCEMENT',
    presale_start_date: '2024-02-20',
    created_at: '2024-01-30',
    tenant_id: 'default',
  },
  {
    id: '7',
    title: 'London Residential Tower',
    description: 'Completed luxury residential project in central London.',
    location: 'London, UK',
    target_amount: 10000000,
    raised_amount: 10000000,
    minimum_investment: 5000,
    expected_return: 12.0,
    duration_months: 24,
    image_url: 'https://images.pexels.com/photos/380769/pexels-photo-380769.jpeg?auto=compress&cs=tinysrgb&w=800',
    status: 'FINISHED',
    created_at: '2023-06-01',
    tenant_id: 'default',
  },
];

export const mockInvestments: Investment[] = [
  {
    id: '1',
    user_id: 'user1',
    project_id: '1',
    amount: 5000,
    tokens: 500,
    status: 'confirmed',
    created_at: '2024-01-15',
    project: mockProjects[0],
  },
  {
    id: '2',
    user_id: 'user1',
    project_id: '2',
    amount: 10000,
    tokens: 400,
    status: 'confirmed',
    created_at: '2024-01-10',
    project: mockProjects[1],
  },
  {
    id: '3',
    user_id: 'user1',
    project_id: '3',
    amount: 3000,
    tokens: 600,
    status: 'confirmed',
    created_at: '2024-01-05',
    project: mockProjects[2],
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    user_id: 'user1',
    type: 'investment',
    amount: 5000,
    status: 'completed',
    created_at: '2024-01-15',
    description: 'Investment in Manhattan Luxury Condos',
  },
  {
    id: '2',
    user_id: 'user1',
    type: 'investment',
    amount: 10000,
    status: 'completed',
    created_at: '2024-01-10',
    description: 'Investment in Miami Beach Resort',
  },
  {
    id: '3',
    user_id: 'user1',
    type: 'transfer',
    amount: -2000,
    status: 'completed',
    created_at: '2024-01-05',
    description: 'Token transfer to external wallet',
  },
  {
    id: '4',
    user_id: 'user1',
    type: 'investment',
    amount: 3000,
    status: 'completed',
    created_at: '2024-01-01',
    description: 'Investment in Austin Tech Campus',
  },
];

export const mockPortfolio: Portfolio = {
  total_invested: 18000,
  current_value: 20700,
  total_return: 2700,
  return_percentage: 15.0,
  active_investments: 3,
};